WORKDIR="/data/srv/aperezca/Monitoring/queries/scale_test_monitoring"
OUTDIR="/data/srv/aperezca/Monitoring/out/scale_test_monitoring"
MAKEHTMLDIR="/data/srv/aperezca/Monitoring/make_html/scale_test_monitoring"
HTMLDIR="/data/srv/aperezca/Monitoring/HTML/scale_test_monitoring"
WEBPATH="https://cms-htcondor-monitor.web.cern.ch/cms-htcondor-monitor/aperezca/HTML/scale_test_monitoring/"
